services:
  spark-worker:
    image: mds-spark:3.12
    container_name: spark-worker
    network_mode: host
    restart: unless-stopped
    environment:
      - SPARK_MASTER_URL=spark://192.168.8.10:7077
      - SPARK_WORKER_HOST=192.168.8.4
      - SPARK_WORKER_PORT=7078
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_LOCAL_IP=192.168.8.4
      - SPARK_LOCAL_HOSTNAME=192.168.8.4
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - SPARK_WORKER_OPTS=-Dspark.worker.resource.gpu.amount=1 -Dspark.worker.resource.gpu.discoveryScript=/opt/spark-apps/getGpusResources.sh
    gpus: all
    volumes:
      - .:/opt/spark-apps
    command:
      [
        "/usr/local/lib/python3.12/site-packages/pyspark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://192.168.8.10:7077"
      ]

  stream-processor:
    container_name: stream-worker
    build: ./streaming-app
    network_mode: host # Switched to host mode so it can route to Kafka natively
    environment:
      - KAFKA_BROKER=192.168.8.10:9092
      - POSTGRES_DB=192.168.8.8

  datanode:
    container_name: hadoop_worker
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    network_mode: host # Host mode prevents internal Docker NAT translation errors with HDFS
    environment:
      - SERVICE_PRECONDITION=192.168.8.10:9870 # Points to NameNode Web UI
      - CORE_CONF_fs_defaultFS=hdfs://192.168.8.10:9000
    volumes:
      - ./hadoop_data:/hadoop/dfs/data
